# Generated by Django 4.0.3 on 2022-04-02 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Type', models.CharField(choices=[('IE', 'Islamic Economical System'), ('SO', 'Islamic Social System'), ('IF', 'Islamic Fatwah')], default='Islamic Economical System', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phoneNumber', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CommonUserAccount',
            fields=[
                ('usermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectApi.usermodel')),
                ('is_commonUser', models.BooleanField(default=False)),
            ],
            bases=('projectApi.usermodel',),
        ),
        migrations.CreateModel(
            name='PreacherAccount',
            fields=[
                ('usermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectApi.usermodel')),
                ('specialization', models.TextField()),
                ('certification', models.FileField(upload_to='Certification')),
                ('is_preacher', models.BooleanField(default=False)),
            ],
            bases=('projectApi.usermodel',),
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoFile', models.FileField(upload_to='Videos')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('uploaded_date', models.DateTimeField(auto_now=True)),
                ('Like_ratio', models.IntegerField()),
                ('Dislike_ratio', models.IntegerField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApi.channelmodel')),
                ('videoCategory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projectApi.videocategorymodel')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApi.preacheraccount')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('commented_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projectApi.usermodel')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApi.videomodel')),
            ],
        ),
        migrations.AddField(
            model_name='channelmodel',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApi.preacheraccount'),
        ),
    ]
