# Generated by Django 4.0.4 on 2022-05-15 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Type', models.CharField(choices=[('IE', 'Islamic Economical System'), ('SO', 'Islamic Social System'), ('IF', 'Islamic Fatwah')], default='Islamic Economical System', max_length=100)),
                ('Thumbnail', models.ImageField(blank=True, null=True, upload_to='Channels/Thumbnail')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='Channels/Thumbnail')),
                ('about', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.IntegerField()),
                ('address', models.TextField(blank=True, null=True)),
                ('specialization', models.TextField(blank=True, null=True)),
                ('certification', models.FileField(blank=True, null=True, upload_to='Certification')),
                ('is_preacher', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoFile', models.FileField(upload_to='Videos')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('uploaded_date', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApi.channelmodel')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApi.usermodel')),
                ('videoCategory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projectApi.videocategorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_view', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projectApi.usermodel')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view', to='projectApi.videomodel')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_subscribed', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApi.channelmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApi.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_liked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='projectApi.videomodel')),
            ],
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_disliked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApi.usermodel')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislike', to='projectApi.videomodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('commented_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projectApi.usermodel')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApi.videomodel')),
            ],
        ),
        migrations.AddField(
            model_name='channelmodel',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApi.usermodel'),
        ),
    ]
