# Generated by Django 4.0.4 on 2022-04-13 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='Dislike_ratio',
        ),
        migrations.RemoveField(
            model_name='videomodel',
            name='Like_ratio',
        ),
        migrations.AddField(
            model_name='channelmodel',
            name='Thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='Channels/Thumbnail'),
        ),
        migrations.AddField(
            model_name='channelmodel',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channelmodel',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='Channels/Thumbnail'),
        ),
        migrations.AddField(
            model_name='channelmodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_view', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projectApi.usermodel')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view', to='projectApi.videomodel')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_subscribed', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApi.channelmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApi.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_liked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='projectApi.videomodel')),
            ],
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_disliked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApi.usermodel')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislike', to='projectApi.videomodel')),
            ],
        ),
    ]
