# Generated by Django 4.0.4 on 2022-05-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApi', '0003_alter_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='videoThumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='Videos/thumbnails'),
        ),
    ]
