# Generated by Django 4.0.4 on 2022-06-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApi', '0008_userwarning'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userwarning',
            name='is_seen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
