# Generated by Django 4.0.4 on 2022-06-24 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApi', '0009_alter_userwarning_is_seen'),
        ('projectApi', '0009_usermodel_user_type_alter_userwarning_is_seen'),
    ]

    operations = [
    ]
